mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: latest
  pullPolicy: IfNotPresent

config:
  exporters:
    debug:
      verbosity: detailed
      sampling_initial: 5
      sampling_thereafter: 200

  service:
    pipelines:
      logs:
        receivers: [otlp]
        processors: []
        exporters: [debug]
      metrics:
        receivers: [otlp]
        processors: []
        exporters: [debug]
      traces:
        receivers: [otlp]
        processors: []
        exporters: [debug]

resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
