apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-webapp-monitor
  namespace: monitoring
  labels:
    app: nginx-webapp-monitor
spec:
  selector:
    matchLabels:
      app: nginx-webapp
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http 