version: '3'

services:
  demo-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    # Volumes can be uncommented during development
    # volumes:
    #  - ./src:/app/src